version: '3'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - redis
    container_name: platyverse  
  redis:
    image: redis
  ngrok:
    build:
      context: .
      dockerfile: Dockerfile.ngrok
    links:
      - web




