# Generated by Django 4.2.3 on 2023-08-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='room_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_system_user',
            field=models.BooleanField(default=False),
        ),
    ]
